module YARD
  module Registry
  end

  module Tags
    module TypesExplainer
      class Parser
      end

      class Type
      end

      class CollectionType < Type
      end

      class FixedCollectionType < CollectionType
      end

      class HashCollectionType < Type
      end
    end
  end

  module CodeObjects
    type t = ModuleObject | ClassObject | MethodObject
    class Base
      def attributes: () -> { class: Hash[Symbol, untyped], instance: Hash[Symbol, untyped] }
    end
    class NamespaceObject < Base
    end
    class ModuleObject < NamespaceObject
    end
    class ClassObject < NamespaceObject
    end
    class MethodObject < Base
    end
  end
end
